# Generated by Django 2.2.4 on 2019-08-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20190809_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
